FROM maven:3.8.5-openjdk-17 AS builder
WORKDIR application

COPY ./ ./
RUN mvn clean package -DskipTests

ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM eclipse-temurin:17-jre-alpine
WORKDIR application
COPY --from=builder application/dependencies/ ./
COPY --from=builder application/spring-boot-loader/ ./
COPY --from=builder application/snapshot-dependencies/ ./
COPY --from=builder application/application.jar ./
ENTRYPOINT exec java -Xmx128m -Xms256m -Xss256k -jar /application/application.jar